install.packages("igraph")
library("igraph")
actors <- read.table("ga_actors.csv", header = TRUE, sep = ",")
edgelist <- read.table("ga_edgelist.csv", header = TRUE, sep = ",")
g <- graph.data.frame(edgelist, directed=TRUE, vertices=actors)
g <- simplify(g)
wtg =walktrap.community(g, weights = E(g)$weight, steps = 4, merges = TRUE, modularity = TRUE, membership = TRUE)
colors <- rainbow(max(membership(fc)))
plot(g,edge.arrow.size=.2,vertex.color=colors[membership(wtg)], layout=lay)
