install.packages("igraph")
library("igraph")
actors <- read.table("ga_actors.csv", header = TRUE, sep = ",")
edgelist <- read.table("c:/ga_edgelist.csv", header = TRUE, sep = ",")
g <- graph.data.frame(edgelist, directed=TRUE, vertices=actors)
g <- simplify(g)
set.seed(100)
lay <- layout.kamada.kawai(g)
fc <- edge.betweenness.community(g)
fc$modularity
memb <- community.to.membership(g, fc$merges, which.max(fc$modularity))
plot(g, layout=lay, vertex.size=5, vertex.label=NA, vertex.color=memb$membership+1,asp=FALSE)
